{{- if .Values.assets.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "remnashop.fullname" . }}-assets
  labels:
    {{- include "remnashop.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - {{ .Values.assets.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.assets.persistence.storageClass }}
  storageClassName: {{ .Values.assets.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.assets.persistence.size }}
{{- end }}