{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnashop.fullname" . }}-secrets
  labels:
    {{- include "remnashop.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_CRYPT_KEY: {{ .Values.secrets.appCryptKey | quote }}
  BOT_TOKEN: {{ .Values.secrets.botToken | quote }}
  BOT_SECRET_TOKEN: {{ .Values.secrets.botSecretToken | quote }}
  BOT_OWNER_ID: {{ .Values.secrets.botOwnerId | quote }}
  BOT_SUPPORT_USERNAME: {{ .Values.secrets.botSupportUsername | quote }}
  REMNAWAVE_TOKEN: {{ .Values.secrets.remnawaveToken | quote }}
  REMNAWAVE_WEBHOOK_SECRET: {{ .Values.secrets.remnawaveWebhookSecret | quote }}
{{- end }}